version: '3.1'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
